module.exports = {
    NULL_VALUE: '필요한 값이 없습니다',
    OUT_OF_VALUE: '파라미터 값이 잘못되었습니다',
    SERVER_ERROR : "서버에러입니다",
    EMPTY_TOKEN : "토큰이 존재하지 않습니다",
    NO_UNAUTH : "승인이 나지 않았습니다. 관리자에게 문의바랍니다",
    YOUR_EXITED : "퇴직 처리된 계정입니다. 관리자에게 문의바랍니다",
    MISS_MATCH_PW : "로그인 정보가 일치하지 않습니다",
    MISS_MATCH_PW2 : "비밀번호가 일치하지 않습니다",
    ALREADY_ID : "유저가 이미 존재합니다",
    AVAILABLE_ID : "사용가능한 아이디 입니다",
    NO_USER : "유저가 존재하지 않습니다",
    CREATED_USER : "회원가입 성공입니다",
    LOGIN_SUCCESS : "로그인 성공했습니다",
    SUCCESS_LOGOUT : "로그아웃 되었습니다.",
    WITHDRAWAL_SUCCESS : "회원탈퇴 되었습니다.",
    SUCCESS_TOKEN_REPLACEMENT : "토큰을 재발급했습니다",
    SUCCESS_UPDATE_AVAILABLE : "연결 상태가 바뀌었습니다",
    EXPIRED_TOKEN : "토큰이 만료되었습니다",
    INVALID_TOKEN : "토큰이 잘못되었습니다",
    PASSWD_SUCCESS : "비밀번호 변경되었습니다.",
    ATTEND_START_SUCCESS : "출근시간을 기록했습니다.",
    ATTEND_END_SUCCESS : "퇴근시간을 기록했습니다.",
    DB_ERROR : "존재하지 않는 회사입니다",
    SUCCESS_GET_COMPANY : "존재하는 회사입니다",
    SUCCESS_CREATE_COMPANY : "회사를 생성하였습니다",
    FAIL_CREATE_COMPANY : "회사 정보를 정확히 입력하세요",
    SUCCESS : "성공",
    SUCCESS_GET_INFO : "회원정보를 가져왔습니다",
    SUCCESS_EDIT_INFO : "회원정보를 수정했습니다",
    CANNOT_FIND_PARTID : "잘못된 파티 아이디입니다",
    SUCCESS_GET_DEP : "부서 리스트를 가져왔습니다",
    SUCCESS_GET_ATTEND : "근태 현황을 가져왔습니다",
    EMPTY_DATE : "날짜가 명확하지 않습니다",
    SUCCESS_GET_SIGNLIST : "결재라인 리스트를 가져왔습니다.",
    SUCCESS_GET_XLIST : "결재라인 미추가 리스트를 가져왔습니다.",
    SUCCESS_MAKE_SIGN : "결재라인을 신규생성했습니다.",
    DELETE_SIGN : "결재선을 삭제했습니다.",
    PUT_SIGN_LIST : "결재선을 수정했습니다.",
    SUCCESS_GET_MYSIGN : "결재라인을 가져왔습니다.",
    SUCCESS_WRITE_JOURNAL : '업무일지를 등록했습니다',
    SUCCESS_GET_MYJOURNAL : "당일 업무일지를 가져왔습니다",
    SUCCESS_GET_APPROVE_FOR : '결재해야할 문서 목록을 가져왔습니다',
    SUCCESS_GET_APPROVE_FOR_DETAIL : '결재할 문서 상세내역을 가져왔습니다',
    SUCCESS_GET_APPROVE_STATUS : '결재자 결재 상황을 가져왔습니다',
    SUCCESS_UPDATE_APPROVE : '결재를 완료했습니다',
    SUCCESS_GET_APPROVE_WRITTEN : '상신문서를 가져왔습니다',
    SUCCESS_POST_APPROVE_OTHER_GOODS : '기타품의서 결재를 올렸습니다',
    SUCCESS_POST_APPROVE_FAMILY_EVENTS : '경조사비 결재를 올렸습니다',
    SUCCESS_POST_APPROVE_WORK_EXPENSES : '업무비용 결재를 올렸습니다',
    SUCCESS_POST_APPROVE_HOLIDAY : '휴가신청서 결재를 올렸습니다',
    SUCCESS_GET_MESSAGE_RECEIVED : '받은 쪽지 목록을 가져왔습니다',
    SUCCESS_GET_USERLIST : '유저 목록을 가져왔습니다',
    SUCCESS_SEND_MESSAGE : '메시지를 전송했습니다.',
    SUUCESS_POST_APPROVE_HOLIDAY : '휴가신청서 결재를 올렸습니다',
    SUCCESS_GET_SCHEDULE_LIST : '프로젝트 참여 목록을 가져왔습니다.',
    SUCCESS_GET_MESSAGE_SENDED : '보낸 쪽지 목록을 가져왔습니다',
    SUCCESS_GET_EMPLOYEE_LIST : '사원 목록을 가져왔습니다.',
    SUCCESS_GET_ADMIN_STATUS : '관리자용 근태현황을 가져왔습니다',
    SUCCESS_GET_ADMIN_TASK : '업무 관리 일지를 가져왔습니다',
    SUCCESS_GET_ADMIN_PROJECTLIST : '프로젝트 리스트를 가져왔습니다',
    SUCCESS_PUT_ADMIN_PROJECTEDIT : '프로젝트를 수정했습니다',
    SUCCESS_DELETE_ADMIN_PROJECT : '프로젝트를 삭제했습니다',
    SUCCESS_TRANS_INVITATION : '초대장을 보냈습니다.',
    SUCCESS_GET_ANNUAL_LIST : '연차 관리 리스트를 가져왔습니다',
    SUCCESS_PUT_ANNUAL : '연차를 수정했습니다',
    SUCCESS_GET_NOTICE : '공지사항을 가져왔습니다',
    SUCCESS_POST_FCM_TOKEN : 'FCM 서버용 토큰을 등록했습니다',
    SUCCESS_LOGOUT_TO_ERASE_FCMTOKEN : 'FCM 토큰을 삭제했습니다',
    SUCCESS_CANCEL_APPROVAL : '상신 취소를 했습니다.',
    SUCCESS_DELETE_APPROVAL : '상신 취소된 문서를 삭제했습니다.',
    SUCCESS_GET_ORG_LIST : '조직도에 대한 회원정보를 가져왔습니다',
    SUCCESS_WRITE_COMMENT : '업무일지 의견을 작성했습니다.',
    SUCCESS_READ_COMMENT : '업무일지 의견을 가져왔습니다',
    SUCCESS_GET_FILELIST : '첨부파일 리스트를 가져왔습니다',
    EMPTY_PARTYID : 'PartyID가 없습니다.'

};